<h4> Lakukan Latihan Berikut </h4>


1. Jika Anda ingin mengundang teman anda untuk makan malam, siapa yang akan anda undang ? Buatlah daftar (list) yang menyertakan setidaknya $5$ orang yang ingin anda undang untuk makan malam. Kemudian gunakan daftar (list) tersebut untuk mencetak pesan kepada mereka bahwa anda mengundang untuk makan malam. contoh : **Halo Rudi, aku mengundangmu untuk makan malam**

2. Anda baru saja mendengar bahwa salah satu teman Anda tidak dapat hadir makan malam. Oleh karena itu Anda perlu mengirimkan undangan baru. Siapakah yang ada di pikiran anda untuk diundang. <br>
    - Ubah daftar Anda, ganti nama tamu yang tidak bisa hadir dengan nama baru yang Anda undang. <br>
    - Cetak undangan ke-2 dengan nama tamu yang baru dalam makan malam tersebut. <br>

3. Anda baru saja menemukan meja makan yang lebih besar, jadi sekarang lebih banyak ruang tersedia. Pikirkan 3 tamu lagi untuk anda undang makan malam.

    - Gunakan **`insert ()`** untuk menambahkan satu tamu baru ke awal daftar Anda.
    - Gunakan **`insert ()`** untuk menambahkan satu tamu baru ke tengah daftar Anda.
    - Gunakan **`append ()`** untuk menambahkan satu tamu baru ke akhir daftar Anda.
    - Cetaklah undangan baru untuk 3 tamu yang akan diundang makan malam dan   cetaklah pesan ke tamu yang sudah Anda undang sebelumnya untuk memberi tahu bahwa akan ada tambahan anggota dikarenakan meja makan dapat menampung banyak orang.

4. Anda baru saja mendapat konfirmasi bahwa ada kesalahan reservasi untuk acara makan malam anda. Meja anda hanya dapat menampung 2 orang tamu.
    - Mulailah dengan program dari Latihan 3. Tambahkan baris baru yang mencetak pesan yang mengatakan bahwa Anda hanya dapat mengundang dua orang untuk makan malam.
    - Pikirkan siapa saja 2 tamu yang tetap diundang, Gunakan **`remove()`** untuk menghapus tamu dari daftar Anda satu per satu sehingga hanya 2 nama tetap ada dalam daftar tersebut. Setiap kali Anda memunculkan nama dari daftar tersebut, cetaklah pesan kepada tamu anda dan beri tahu mereka bahwa Anda menyesal tidak dapat mengundang mereka untuk makan malam.
    - Cetak pesan kepada 2 orang yang masih ada di daftar Anda, beritahukan mereka bahwa mereka masih diundang.
    - Gunakan **`del`** untuk menghapus dua nama terakhir dari daftar Anda. Cetak daftar Anda untuk memastikan bahwa daftar tersebut kosong.<br>
   Selamat mencoba

In [ ]:
# 1
tamu = ['Andi', 'Bayu', 'Cika', 'Dini', 'Erlin']
for nama in tamu:
  print("Halo {}, aku mengundangmu untuk makan malam".format(nama))

Halo Andi, aku mengundangmu untuk makan malam
Halo Bayu, aku mengundangmu untuk makan malam
Halo Cika, aku mengundangmu untuk makan malam
Halo Dini, aku mengundangmu untuk makan malam
Halo Erlin, aku mengundangmu untuk makan malam

In [ ]:
# 2
tamu[2] = 'Ceyi'
for nama in tamu:
  print(f"Halo {nama}, aku mengundangmu untuk makan malam")

Halo Andi, aku mengundangmu untuk makan malam
Halo Bayu, aku mengundangmu untuk makan malam
Halo Ceyi, aku mengundangmu untuk makan malam
Halo Dini, aku mengundangmu untuk makan malam
Halo Erlin, aku mengundangmu untuk makan malam

In [ ]:
# 3
tamu.insert(0, 'Farhan')
print(tamu)
tamu.insert(3, 'Gilang')
print(tamu)
tamu.append('Hanis')
print(tamu)

['Farhan', 'Andi', 'Bayu', 'Ceyi', 'Dini', 'Erlin']
['Farhan', 'Andi', 'Bayu', 'Gilang', 'Ceyi', 'Dini', 'Erlin']
['Farhan', 'Andi', 'Bayu', 'Gilang', 'Ceyi', 'Dini', 'Erlin', 'Hanis']

In [ ]:
for nama in tamu:
  if (nama in ['Farhan', 'Gilang', 'Hanis']):
    print("Halo {}, aku mengundangmu untuk makan malam".format(nama))
  else:
    print("Halo {}, akan ada tambahan anggota dikarenakan meja makan dapat menampung banyak orang".format(nama))

Halo Farhan, aku mengundangmu untuk makan malam
Halo Andi, akan ada tambahan anggota dikarenakan meja makan dapat menampung banyak orang
Halo Bayu, akan ada tambahan anggota dikarenakan meja makan dapat menampung banyak orang
Halo Gilang, aku mengundangmu untuk makan malam
Halo Ceyi, akan ada tambahan anggota dikarenakan meja makan dapat menampung banyak orang
Halo Dini, akan ada tambahan anggota dikarenakan meja makan dapat menampung banyak orang
Halo Erlin, akan ada tambahan anggota dikarenakan meja makan dapat menampung banyak orang
Halo Hanis, aku mengundangmu untuk makan malam

In [ ]:
# 4
for nama in tamu:
  print("Halo {}, maaf karena ada kesalahan reservasi sehingga aku hanya bisa mengundang 2 orang untuk makan malam".format(nama))

Halo Farhan, maaf karena ada kesalahan reservasi sehingga aku hanya bisa mengundang 2 orang untuk makan malam
Halo Andi, maaf karena ada kesalahan reservasi sehingga aku hanya bisa mengundang 2 orang untuk makan malam
Halo Bayu, maaf karena ada kesalahan reservasi sehingga aku hanya bisa mengundang 2 orang untuk makan malam
Halo Gilang, maaf karena ada kesalahan reservasi sehingga aku hanya bisa mengundang 2 orang untuk makan malam
Halo Ceyi, maaf karena ada kesalahan reservasi sehingga aku hanya bisa mengundang 2 orang untuk makan malam
Halo Dini, maaf karena ada kesalahan reservasi sehingga aku hanya bisa mengundang 2 orang untuk makan malam
Halo Erlin, maaf karena ada kesalahan reservasi sehingga aku hanya bisa mengundang 2 orang untuk makan malam
Halo Hanis, maaf karena ada kesalahan reservasi sehingga aku hanya bisa mengundang 2 orang untuk makan malam

In [ ]:
tamu_diundang = ['Andi', 'Dini'] 
for nama in tamu.copy():
  if nama in tamu_diundang:
    continue
  print("Maaf {}, Aku menyesal tidak dapat mengundang kamu untuk makan malam".format(nama))
  tamu.remove(nama)

Maaf Farhan, Aku menyesal tidak dapat mengundang kamu untuk makan malam
Maaf Bayu, Aku menyesal tidak dapat mengundang kamu untuk makan malam
Maaf Gilang, Aku menyesal tidak dapat mengundang kamu untuk makan malam
Maaf Ceyi, Aku menyesal tidak dapat mengundang kamu untuk makan malam
Maaf Erlin, Aku menyesal tidak dapat mengundang kamu untuk makan malam
Maaf Hanis, Aku menyesal tidak dapat mengundang kamu untuk makan malam

In [ ]:
for nama in tamu:
  print("Halo {}, kamu masih aku undang untuk makan malam".format(nama))

Halo Andi, kamu masih aku undang untuk makan malam
Halo Dini, kamu masih aku undang untuk makan malam

In [ ]:
del tamu[:]
print(tamu)

[]

<h4> Lakukan Latihan Berikut </h4>




1. Gunakan dictionary untuk menyimpan informasi tentang orang yang Anda kenal.
Simpan nama depan, nama belakang, umur, dan kota tempat mereka tinggal. Anda
akan memiliki kunci seperti first_name, last_name, age, dan city. Cetak masing-masing informasi yang disimpan dalam dictionary tersebut.

2. Gunakan dictionary untuk menyimpan nomor favorit orang.
Pikirkan lima nama, dan gunakan sebagai kunci dalam dictionary anda. Pikirkan favorit
nomor untuk setiap orang, dan simpan masing-masing sebagai nilai dalam dictionary. Cetaklah setiap nama orang dan nomor favoritnya.

3. Buatlah function yang menyimpan informasi tentang mobil dalam dictionary. function tersebut harus selalu menerima nama produksi dan model.  Panggil function dengan informasi yang diperlukan dan dua pasangan, nama-nilai lainnya, seperti warna atau fitur (opsional). Fuction yang telah anda buat, harus berfungsi dengan cara memanggilnya seperti berikut:
         
          car = make_car('subaru', 'outback', color='blue', tow_package=True)

In [ ]:
# 1
teman = {'first_name':'Raden', 'last_name':'Wijaya', 'age':21, 'city':'Jakarta'}
for key in teman:
  print(key, ' -> ', teman[key])

first_name  ->  Raden
last_name  ->  Wijaya
age  ->  21
city  ->  Jakarta

In [ ]:
# 2
kontak = {'Andi':6281234567231, 'Bela':6282369871666, 'Coki':6285334999888, 'Denise':6281222876554, 'Edi':6287215678666}
for key_name in kontak:
  print("Nama = ", key_name, ", Nomor = ", kontak[key_name])

Nama =  Andi , Nomor =  6281234567231
Nama =  Bela , Nomor =  6282369871666
Nama =  Coki , Nomor =  6285334999888
Nama =  Denise , Nomor =  6281222876554
Nama =  Edi , Nomor =  6287215678666

In [ ]:
# 3
def make_car(produksi, model, color='blue', tow_package=True):
  car = {'production':produksi, 
         'model':model,
         'color':color,
         'tow package':tow_package}
  return car

In [ ]:
car = make_car('subaru', 'outback', color='blue', tow_package=True)
print(car)

{'production': 'subaru', 'model': 'outback', 'color': 'blue', 'tow package': True}

<h4> Lakukan Latihan Berikut </h4>




1. Bacalah dataset 'retail_raw_test.csv' dan tampilkan 10 elemen pertama dataset tersebut dengan index columnnya yaitu order_date.

2. Hapuslah kolom order_id dan product_id dan tampilkan data retail pada kota Jakarta Pusat atau Yogyakarta

3. Buatlah kolom "total_price" sebagai hasil perkalian quantity dengan item_price dan "city/province" dari gabungan city & province. kemudian hapus kolom city dan province.

4. Tampilkan retail yang terjadi mulai tanggal 1 Agustus 2019 sampai 30 Agustus 2019

5. Tampilkan banyakanya tiap brand dengan mengelompokan data berdasarkan kolom brand

In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
# 1
import pandas as pd

path_data = "/content/gdrive/MyDrive/Summer Program/Meet 3 (Mas Doni)/Data/"

In [ ]:
df = pd.read_csv(path_data + "retail_raw_test.csv", index_col='order_date')
df.head(10)

            order_id  customer_id  ... item_price product_id
order_date                         ...
2019-12-11   1730350        13447  ...     113000      P1374
2019-10-18   1704211        16128  ...     747000      P1679
2019-08-07   1679695        16225  ...     590000      P1708
2019-04-18   1642990        16022  ...    2445000      P2279
2019-04-16   1642138        12720  ...    6312000      P2803
2019-12-08   1728226        15861  ...     590000      P2102
2019-04-21   1643581        17625  ...     240000      P1768
2019-08-23   1685443        14854  ...   13995000      P3390
2019-10-20   1704610        13435  ...     590000      P3022
2019-03-04   1630102        18225  ...     205000      P2443

[10 rows x 8 columns]

In [ ]:
# 2
df = df.drop(columns=['order_id', 'product_id'])
df[(df['city']=='Jakarta Pusat') | (df['city']=='Yogyakarta')]

            customer_id           city  ... quantity item_price
order_date                              ...
2019-10-18        16128  Jakarta Pusat  ...       12     747000
2019-08-07        16225     Yogyakarta  ...        6     590000
2019-04-18        16022  Jakarta Pusat  ...        4    2445000
2019-01-13        17913  Jakarta Pusat  ...        1    1045000
2019-07-23        12747  Jakarta Pusat  ...       24    2375000
...                 ...            ...  ...      ...        ...
2019-12-05        13319     Yogyakarta  ...       12    1745000
2019-11-04        16133  Jakarta Pusat  ...        2    2987000
2019-10-22        13644     Yogyakarta  ...       12     740000
2019-09-24        17675  Jakarta Pusat  ...        4    1745000
2019-10-08        16279  Jakarta Pusat  ...        4     740000

[736 rows x 6 columns]

In [ ]:
# 3
df['total_price'] = df['quantity']*df['item_price']
df['city/province'] = df['city'] + " / " + df['province']
df

            customer_id  ...                city/province
order_date               ...
2019-12-11        13447  ...      Surakarta / Jawa Tengah
2019-10-18        16128  ...  Jakarta Pusat / DKI Jakarta
2019-08-07        16225  ...      Yogyakarta / Yogyakarta
2019-04-18        16022  ...  Jakarta Pusat / DKI Jakarta
2019-04-16        12720  ...              Denpasar / Bali
...                 ...  ...                          ...
2019-10-17        16395  ...       Semarang / Jawa Tengah
2019-01-08        12748  ...  Jakarta Utara / DKI Jakarta
2019-11-13        16885  ...          Bekasi / Jawa Barat
2019-07-03        13571  ...  Jakarta Utara / DKI Jakarta
2019-11-26        14505  ...  Jakarta Timur / DKI Jakarta

[3802 rows x 8 columns]

In [ ]:
# 4
df = df.sort_index()
df.loc['2019-08-01':'2019-08-31']

            customer_id  ...                  city/province
order_date               ...
2019-08-01        15719  ...    Jakarta Barat / DKI Jakarta
2019-08-01        16814  ...          Surabaya / Jawa Timur
2019-08-01        15150  ...    Jakarta Pusat / DKI Jakarta
2019-08-01        17696  ...        Surakarta / Jawa Tengah
2019-08-01        15719  ...    Jakarta Barat / DKI Jakarta
...                 ...  ...                            ...
2019-08-30        13451  ...    Jakarta Timur / DKI Jakarta
2019-08-30        17092  ...  Jakarta Selatan / DKI Jakarta
2019-08-30        16880  ...            Bekasi / Jawa Barat
2019-08-30        16271  ...  Jakarta Selatan / DKI Jakarta
2019-08-30        17231  ...            Bekasi / Jawa Barat

[289 rows x 8 columns]

In [ ]:
# 5
df.groupby('brand').count()

         customer_id  city  province  ...  item_price  total_price  city/province
brand                                 ...
BRAND_A          231   231       231  ...         231          231            231
BRAND_B          195   195       195  ...         195          195            195
BRAND_C          286   286       286  ...         286          286            286
BRAND_D          148   148       148  ...         148          148            148
BRAND_E           69    69        69  ...          69           69             69
BRAND_F          151   151       151  ...         151          151            151
BRAND_G          165   165       165  ...         165          165            165
BRAND_H          206   206       206  ...         206          206            206
BRAND_I           48    48        48  ...          48           48             48
BRAND_J          182   182       182  ...         182          182            182
BRAND_K           22    22        22  ...          22           22             22
BRAND_L          212   212       212  ...         212          212            212
BRAND_M          133   133       133  ...         133          133            133
BRAND_N           32    32        32  ...          32           32             32
BRAND_O           19    19        19  ...          19           19             19
BRAND_P          401   401       401  ...         401          401            401
BRAND_Q            5     5         5  ...           5            5              5
BRAND_R          329   329       329  ...         329          329            329
BRAND_S          532   532       532  ...         532          532            532
BRAND_T          120   120       120  ...         120          120            120
BRAND_U            6     6         6  ...           6            6              6
BRAND_V           89    89        89  ...          89           89             89
BRAND_W          198   198       198  ...         198          198            198
BRAND_Y            3     3         3  ...           3            3              3
BRAND_Z           20    20        20  ...          20           20             20

[25 rows x 7 columns]