# GDrive Connection

In [ ]:
# Mengkoneksikan colab dengan gdrive
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

# Import Library

In [ ]:
# Import Library
import os
import pandas as pd

In [ ]:
# Setting path
path = '/content/gdrive/My Drive/narasio_data/Summer Program/Meet 6 (Mbak Wimi)/Data/'

# Cek directory
os.listdir(path)

['reciepts.csv', 'customer.csv']

# **Latihan (Probabilitas)**

Asosiasi  Olah Raga Nasional melakukan survei terhadap orang-orang berusia 7 tahun atau lebih tua tentang partisipasi dalam kegiatan olahraga (Abstrak Statistik Amerika Serikat: 2002).
Jumlah penduduk pada kelompok umur ini dilaporkan sebanyak 248,5 juta, dengan 120,9 juta laki-laki dan 127,6 juta perempuan. Jumlah peserta untuk lima aktivitas olahraga teratas adalah \\

|Activity| Male |Female|
|----|----|-----|
Bicycle riding |22.2| 21.0
Camping |25.6 |24.3
Exercise walking| 28.7 |57.7
Exercising with equipment |20.4 |24.4
Swimming |26.4| 34.4

a. Untuk wanita yang dipilih secara acak, perkirakan probabilitas partisipasi di masing-masing 5 kegiatan olahraga? \\
b. Untuk orang yang dipilih secara acak, berapa probabilitas orang tersebut berpartisipasi olahraga excercise walking?

In [ ]:
# Jawaban A
# Menerapkan dictionary untuk membuat dataframe
df_probabilitas = pd.DataFrame({'Activity': ['Bicycle riding', 'Camping', 'Exercise walking', 'Exercising with equipment', 'Swimming'],
                                'Male': [22.2, 25.6, 28.7, 20.4, 26.4],
                                'Female': [21.0, 24.3, 57.7, 24.4, 34.4]})

# Display dataframe
df_probabilitas

                    Activity  Male  Female
0             Bicycle riding  22.2    21.0
1                    Camping  25.6    24.3
2           Exercise walking  28.7    57.7
3  Exercising with equipment  20.4    24.4
4                   Swimming  26.4    34.4

**Referensi Jawaban 1**

In [ ]:
prob_female = df_probabilitas.groupby('Activity')['Female'].sum() / sum(df_probabilitas['Female'])

print("Probabilitas wanita yang dipilih secara acak untuk setiap kegiatan olahraga adalah")
print(prob_female)

Probabilitas wanita yang dipilih secara acak untuk setiap kegiatan olahraga adalah
Activity
Bicycle riding               0.129790
Camping                      0.150185
Exercise walking             0.356613
Exercising with equipment    0.150803
Swimming                     0.212608
Name: Female, dtype: float64

In [ ]:
# Jawaban B
df_probabilitas['Participants'] = df_probabilitas['Female'] + df_probabilitas['Male']

prob_choose = df_probabilitas.groupby('Activity')['Participants'].sum().loc['Exercise walking'] / sum(df_probabilitas['Participants'])

print("Probabilitas orang yang dipilih secara acak untuk kegiatan olahraga Exercise walking adalah " + str(prob_choose))

Probabilitas orang yang dipilih secara acak untuk kegiatan olahraga Exercise walking adalah 0.30305156085584006

**Referensi Jawaban 2**

In [ ]:
# Set activity sebagai index
df_probabilitas_new = df_probabilitas.set_index('Activity')
df_probabilitas_new

                           Male  Female  Participants
Activity
Bicycle riding             22.2    21.0          43.2
Camping                    25.6    24.3          49.9
Exercise walking           28.7    57.7          86.4
Exercising with equipment  20.4    24.4          44.8
Swimming                   26.4    34.4          60.8

In [ ]:
df_probability_new

In [ ]:
# Jawaban A
prob_female = df_probabilitas_new['Female'] / df_probabilitas_new['Female'].sum()

print("Probabilitas wanita yang dipilih secara acak untuk setiap kegiatan olahraga adalah")
print(prob_female)

Probabilitas wanita yang dipilih secara acak untuk setiap kegiatan olahraga adalah
Activity
Bicycle riding               0.129790
Camping                      0.150185
Exercise walking             0.356613
Exercising with equipment    0.150803
Swimming                     0.212608
Name: Female, dtype: float64

In [ ]:
# Jawaban B
df_tot = df_probabilitas_new['Female'] + df_probabilitas_new['Male']

prob_choose = df_tot['Exercise walking'] / df_tot.sum()
print("Probabilitas orang yang dipilih secara acak untuk kegiatan olahraga excercise walking adalah " + str(prob_choose))

Probabilitas orang yang dipilih secara acak untuk kegiatan olahraga excercise walking adalah 0.30305156085584006

# **Latihan (Statistika Deskriptif)**

Untuk lebih memahami materi statistika deskriptif, silakan untuk mencoba latihan ini

Untuk periode 2001–2008, Bristol-Myers Squibb
Company, Inc. melaporkan jumlah (dalam milyaran
dolar) untuk (1) penjualan bersih dan (2) iklan dan
promosi produk \\

| Tahun | Net sales | Iklan |
|----|---|----|
|2001 | 16.612 |1.201|
|2002 |16.208 |1.143|
|2003 |18.653 |1.416|
|2004 |19.380 |1.411|
|2005 |19.207 |1.476|
|2006 |16.208 |1.304|
|2007 |18.193 |1.415|
|2008 |20.597| 1.550|

(a) Tunjukkan berapa rata-rata net sales dan iklan selama 9 tahun? \\
(b) Berapa variasi yang didapatkan untuk net sales dan iklan selama 9 tahun? \\

In [ ]:
# Jawaban A
# Menerapkan dictionary untuk membuat dataframe
df_stat = pd.DataFrame({'Tahun': [2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008],
                        'Net sales': [16.612, 16.208, 18.653, 19.380, 19.207, 16.208, 18.193, 20.597],
                        'Iklan': [1.201, 1.143, 1.416, 1.411, 1.476, 1.304, 1.415, 1.550]})

# Display dataframe
df_stat

   Tahun  Net sales  Iklan
0   2001     16.612  1.201
1   2002     16.208  1.143
2   2003     18.653  1.416
3   2004     19.380  1.411
4   2005     19.207  1.476
5   2006     16.208  1.304
6   2007     18.193  1.415
7   2008     20.597  1.550

In [ ]:
# Rata-rata net sales dan iklan selama 9 tahun
# Mendapatkan mean pada kolom net sales
mean_net_sales = df_stat['Net sales'].mean()

# Mendapatkan mean pada kolom Iklan
mean_iklan= df_stat['Iklan'].mean()

# Display hasil
print("Nilai rata-rata net sales selama 9 tahun adalah " + str(mean_net_sales))
print("Nilai rata-rata iklas selama 9 tahun adalah " + str(mean_iklan))

Nilai rata-rata net sales selama 9 tahun adalah 18.13225
Nilai rata-rata iklas selama 9 tahun adalah 1.3645

**Menggunakan library statistics**

In [ ]:
# Jawaban B
import statistics

# Mendapatkan varian dari masing-masing kolom
print("Varians dari net sales selama 9 tahun adalah :", statistics.variance(df_stat['Net sales']))
print("Varians dari iklan selama 9 tahun adalah :", statistics.variance(df_stat['Net sales']))

Varians dari net sales selama 9 tahun adalah : 2.6826382142857175
Varians dari iklan selama 9 tahun adalah : 2.6826382142857175

**Tidak menggunakan library statistics**

In [ ]:
# Mendapatkan varian dari masing-masing kolom
print("Varians dari net sales selama 9 tahun adalah :", df_stat['Net sales'].var())
print("Varians dari iklan selama 9 tahun adalah :", df_stat['Net sales'].var())

Varians dari net sales selama 9 tahun adalah : 2.6826382142857175
Varians dari iklan selama 9 tahun adalah : 2.6826382142857175

# Latihan (Statistika Deskriptif di bisnis)

Berdasarkan data transaksi dari coffee shop diatas. Carilah persebaran umur berdasarkan mean, dan varian dari customer tersebut. Serta dapatkan modus usia dari customers.

In [ ]:
# Panggil kembali data coffee shop disini

# Read dataset
df_cust = pd.read_csv(path + 'customer.csv')
df_rec = pd.read_csv(path + 'reciepts.csv')

# Join columns (Merging.. Left Join..) 
df_trx = pd.merge(df_cust, df_rec, left_on = 'customer_id', right_on = 'customer_id', how = 'left')

df_trx.head()

   customer_id  home_store  ... unit_price promo_item_yn
0            1           3  ...        3.0             N
1            1           3  ...        3.0             N
2            1           3  ...        2.0             N
3            1           3  ...        2.0             N
4            1           3  ...        3.5             N

[5 rows x 22 columns]

In [ ]:
# Mencari deskripsi data
df_trx.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24853 entries, 0 to 24852
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          24853 non-null  int64
 1   home_store           24853 non-null  int64
 2   customer_first-name  24853 non-null  object
 3   customer_email       24853 non-null  object
 4   customer_since       24853 non-null  object
 5   loyalty_card_number  24853 non-null  object
 6   birthdate            24853 non-null  object
 7   gender               24853 non-null  object
 8   birth_year           24853 non-null  int64
 9   transaction_id       24852 non-null  float64
 10  transaction_date     24852 non-null  object
 11  transaction_time     24852 non-null  object
 12  sales_outlet_id      24852 non-null  float64
 13  staff_id             24852 non-null  float64
 14  instore_yn           24852 non-null  object
 15  order                24852 non-null  float64
 16  line_item_id         24852 non-null  float64
 17  product_id           24852 non-null  float64
 18  quantity             24852 non-null  float64
 19  line_item_amount     24852 non-null  float64
 20  unit_price           24852 non-null  float64
 21  promo_item_yn        24852 non-null  object
dtypes: float64(9), int64(3), object(10)
memory usage: 4.4+ MB

In [ ]:
# Merubah kolom birthdate kedalam format datetime
df_trx['birthdate'] = pd.to_datetime(df_trx['birthdate'])

# Cek perubahan format data
df_trx.dtypes

customer_id                     int64
home_store                      int64
customer_first-name            object
customer_email                 object
customer_since                 object
loyalty_card_number            object
birthdate              datetime64[ns]
gender                         object
birth_year                      int64
transaction_id                float64
transaction_date               object
transaction_time               object
sales_outlet_id               float64
staff_id                      float64
instore_yn                     object
order                         float64
line_item_id                  float64
product_id                    float64
quantity                      float64
line_item_amount              float64
unit_price                    float64
promo_item_yn                  object
dtype: object

In [ ]:
# Mencari usia berdasarkan data birthdate
import datetime as dt

df_trx['day'] = (dt.datetime.now() - df_trx['birthdate']).dt.days

# Untuk mendapatkan tahun maka hari akan dibagi dengan total hari dalam setahun
df_trx['usia'] = df_trx['day'] / 365

# Menampilkan perubahan yang dilakukan
df_trx.head(6)

   customer_id  home_store customer_first-name  ... promo_item_yn    day       usia
0            1           3           Kelly Key  ...             N  25970  71.150685
1            1           3           Kelly Key  ...             N  25970  71.150685
2            1           3           Kelly Key  ...             N  25970  71.150685
3            1           3           Kelly Key  ...             N  25970  71.150685
4            1           3           Kelly Key  ...             N  25970  71.150685
5            1           3           Kelly Key  ...             N  25970  71.150685

[6 rows x 24 columns]

In [ ]:
# Mencari statistika deskriptif dari kolom umur
df_trx['usia'].describe()

count    24853.000000
mean        42.786097
std         15.096091
min         20.252055
25%         29.457534
50%         40.169863
75%         56.000000
max         71.194521
Name: usia, dtype: float64